### ISSUE TITLE
checking balance on bergfuerst with money money

### ISSUE THREAD

**Issue by iSchorsch** [nicolindemann/bergfuerst-moneymoney#2]
Hello,

great plug in! Thank you for your great work, but it does not work for me anymore.
I get this error message:

> bergfuerst.lua:104: attempt to perform arithmetic on local 'balance' (a nil value)

**Comment by nicolindemann** [comment]
@iSchorsch 
Bergfürst had changed their website. The new version should work again.

**Comment by iSchorsch** [comment]
Thank you Nico for your effort! Its greatly appreciated!
The login does now work again beautiful. Unfortunately it is not pulling the correct values from the account. The investments are shown correct, but the values are zero.
Would you mind looking into it again?

**Comment by nicolindemann** [comment]
Are the expected values greater than 999,99? Then maybe it is connected to #1. Try using the new version in the `src` directory on the [develop-branch](https://github.com/nicolindemann/bergfuerst-moneymoney/tree/develop)

**Comment by iSchorsch** [comment]
Yes Nico. The value was greater than 999,99. With the new dev-version everything shows now correct. Thank you for your effort!
